// <auto-generated />
using System;
using AdmDentalOffice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdmDentalOffice.Migrations
{
    [DbContext(typeof(AdmDentalOfficeDataContext))]
    partial class AdmDentalOfficeDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AdmDentalOffice.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AppointmentDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR(10)")
                        .HasColumnName("AppointmentDate");

                    b.Property<int>("Cpf")
                        .HasColumnType("INT")
                        .HasColumnName("Cpf");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR(4)")
                        .HasColumnName("EndTime");

                    b.Property<int>("PatientId")
                        .HasColumnType("INT")
                        .HasColumnName("PatientId");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR(4)")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("AdmDentalOffice.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasMaxLength(60)
                        .HasColumnType("SMALLDATETIME")
                        .HasColumnName("BirthDate");

                    b.Property<int>("Cpf")
                        .HasColumnType("INT")
                        .HasColumnName("Cpf");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR(80)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("AdmDentalOffice.Models.Appointment", b =>
                {
                    b.HasOne("AdmDentalOffice.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_Patient_Appointment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AdmDentalOffice.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
